"""
ear_adapter_kyverno.py — Kyverno EAR Adapter
Wave 2 — System 8. Kubernetes-native policy engine via CRDs.

Key finding: PolicyReport CRYSTALLIZED; image verification is highest-governance surface.
"""
from __future__ import annotations
import json
from dataclasses import dataclass, field
from enum import Enum

class EARState(Enum):
    ACTIVE = "ACTIVE"; CRYSTALLIZED = "CRYSTALLIZED"; ABSENT = "ABSENT"

class GCGForm(Enum):
    NON_ACTIVATION = "NON_ACTIVATION"; ABSENCE = "ABSENCE"; BYPASS = "BYPASS"

@dataclass
class OperationFamily:
    name: str; description: str; declared_layers: list[str]; kyverno_scope: str

@dataclass
class GovernanceLayer:
    name: str; description: str; evidence_field: str | None = None; is_optional: bool = False

@dataclass
class ExecutionInstance:
    operation_family: str; request_id: str; timestamp: str
    policy_matched: bool; webhook_invoked: bool
    policy_report_written: bool; image_verified: bool
    resource_kind: str; namespace: str; result: str | None
    error: str | None; raw: dict = field(default_factory=dict)

@dataclass
class GovernanceDeclaration:
    source: str; strategy: str; description: str

KV_OPERATION_FAMILIES = [
    OperationFamily("policy_evaluation",
        "Admission webhook evaluation against ClusterPolicy/Policy",
        ["cluster_policy", "admission_webhook", "policy_report"], "admission"),
    OperationFamily("background_scan",
        "Background scan of existing resources against policies",
        ["cluster_policy", "policy_report"], "background"),
    OperationFamily("mutation_admission",
        "Mutating admission — patch resource before API server stores it",
        ["cluster_policy", "admission_webhook", "policy_report"], "mutation"),
    OperationFamily("image_verification",
        "Verify container image signatures/attestations via Cosign/Notation",
        ["cluster_policy", "admission_webhook", "image_attestation"], "image"),
    OperationFamily("policy_management",
        "Create/update/delete ClusterPolicy or Policy",
        ["cluster_policy", "admission_webhook"], "management"),
]

KV_GOVERNANCE_LAYERS = {
    "cluster_policy": GovernanceLayer("cluster_policy",
        "ClusterPolicy/Policy CRD declaration", "spec.rules"),
    "admission_webhook": GovernanceLayer("admission_webhook",
        "Admission webhook invocation", "webhookConfiguration"),
    "policy_report": GovernanceLayer("policy_report",
        "PolicyReport/ClusterPolicyReport CRD recording evaluation results", None),
    "image_attestation": GovernanceLayer("image_attestation",
        "Cosign/Notation attestation verification — constitutive for image verification", None),
}

class KyvernoEARAdapter:
    GOVERNANCE_DECLARATION = GovernanceDeclaration(
        source="Kyverno Documentation + PolicyReport spec + Kyverno GitHub",
        strategy="DECLARED-N",
        description=(
            "N(O) from Kyverno architecture. policy_evaluation N=3. "
            "PolicyReport CRYSTALLIZED: exists as CRD, generated by Kyverno, "
            "but admission decision does not depend on PolicyReport write success. "
            "image_verification: image_attestation is closest to ACTIVE in Wave 2 — "
            "the admission decision explicitly depends on attestation verification result."
        ),
    )

    def __init__(self, policy_reports_enabled: bool = False,
                 webhook_active: bool = True, image_verification_mode: bool = False):
        self._reports = policy_reports_enabled
        self._webhook = webhook_active
        self._image_mode = image_verification_mode

    def collect_operation_families(self): return KV_OPERATION_FAMILIES
    def collect_governance_layers(self, op_family):
        return [KV_GOVERNANCE_LAYERS[n] for n in op_family.declared_layers
                if n in KV_GOVERNANCE_LAYERS]
    def collect_executions(self, op_family):
        return [ExecutionInstance(
            operation_family=op_family.name,
            request_id=f"synthetic:{op_family.name}", timestamp="",
            policy_matched=True, webhook_invoked=self._webhook,
            policy_report_written=self._reports,
            image_verified=(op_family.name == "image_verification"),
            resource_kind="(structural)", namespace="", result=None, error=None, raw={},
        )]

    def assess_k(self, inst):
        k = []
        fam = next((f for f in KV_OPERATION_FAMILIES if f.name == inst.operation_family), None)
        if not fam: return k
        if "cluster_policy" in fam.declared_layers and inst.policy_matched:
            k.append("cluster_policy")
        if "admission_webhook" in fam.declared_layers and inst.webhook_invoked:
            k.append("admission_webhook")
        if "policy_report" in fam.declared_layers and inst.policy_report_written:
            k.append("policy_report")
        if "image_attestation" in fam.declared_layers and inst.image_verified:
            k.append("image_attestation")
        return k

    def assess_ear_state(self, op_family):
        if not self._webhook: return EARState.ABSENT
        # image_verification is CRYSTALLIZED approaching ACTIVE
        # (attestation is constitutive but formal receipt not mandatory-separate)
        return EARState.CRYSTALLIZED

    def get_governance_declaration(self): return self.GOVERNANCE_DECLARATION
