"""
ear_adapter_istio.py — Istio Service Mesh EAR Adapter
Wave 2 — System 9.

Key finding: CRYSTALLIZED with substrate dependency on Kubernetes sidecar injection.
Sidecar injection bypass: pods without sidecars escape Istio governance entirely.
"""
from __future__ import annotations
import json
from dataclasses import dataclass, field
from enum import Enum

class EARState(Enum):
    ACTIVE = "ACTIVE"; CRYSTALLIZED = "CRYSTALLIZED"; ABSENT = "ABSENT"

class GCGForm(Enum):
    NON_ACTIVATION = "NON_ACTIVATION"; ABSENCE = "ABSENCE"; BYPASS = "BYPASS"

@dataclass
class OperationFamily:
    name: str; description: str; declared_layers: list[str]; istio_scope: str

@dataclass
class GovernanceLayer:
    name: str; description: str; evidence_field: str | None = None; is_optional: bool = False

@dataclass
class ExecutionInstance:
    operation_family: str; request_id: str; timestamp: str
    policy_evaluated: bool; sidecar_present: bool
    access_log_written: bool; mtls_verified: bool
    source_principal: str | None; destination: str | None
    result: str | None; error: str | None; raw: dict = field(default_factory=dict)

@dataclass
class GovernanceDeclaration:
    source: str; strategy: str; description: str

IS_OPERATION_FAMILIES = [
    OperationFamily("request_authorization",
        "AuthorizationPolicy evaluation for inbound request",
        ["authorization_policy", "envoy_access_log", "mtls_peer_auth"], "authz"),
    OperationFamily("mtls_handshake",
        "Mutual TLS peer authentication between sidecars",
        ["peer_authentication", "mtls_cert", "envoy_access_log"], "mtls"),
    OperationFamily("traffic_management",
        "VirtualService/DestinationRule routing decision",
        ["virtual_service", "envoy_access_log"], "traffic"),
    OperationFamily("sidecar_injection",
        "Envoy sidecar injection into pod at admission time",
        ["injection_webhook", "envoy_config"], "injection"),
]

IS_GOVERNANCE_LAYERS = {
    "authorization_policy": GovernanceLayer("authorization_policy",
        "AuthorizationPolicy CRD declaration", "spec.rules"),
    "envoy_access_log": GovernanceLayer("envoy_access_log",
        "Envoy proxy access log recording request decisions", None),
    "mtls_peer_auth": GovernanceLayer("mtls_peer_auth",
        "PeerAuthentication policy for mTLS requirements", "spec.mtls"),
    "peer_authentication": GovernanceLayer("peer_authentication",
        "PeerAuthentication CRD for mTLS mode declaration", "spec.mtls.mode"),
    "mtls_cert": GovernanceLayer("mtls_cert",
        "SVID/X.509 certificate used in mTLS handshake", "subjectAltName"),
    "virtual_service": GovernanceLayer("virtual_service",
        "VirtualService routing rule declaration", "spec.http"),
    "injection_webhook": GovernanceLayer("injection_webhook",
        "Istio sidecar injection webhook", "webhookConfiguration"),
    "envoy_config": GovernanceLayer("envoy_config",
        "Envoy proxy configuration generated by istiod", None),
}

class IstioEARAdapter:
    GOVERNANCE_DECLARATION = GovernanceDeclaration(
        source="Istio Documentation + Envoy Access Log spec + Kubernetes Admission Webhook spec",
        strategy="DECLARED-N",
        description=(
            "N(O) from Istio architecture. request_authorization N=3. "
            "CRYSTALLIZED ceiling: Envoy access log exists but admission decision does not depend on write. "
            "Substrate dependency (T019): Istio governance bounded by Kubernetes sidecar injection governance. "
            "Pod without sidecar: BYPASS — all Istio governance absent for that workload."
        ),
    )

    def __init__(self, access_log_enabled: bool = False,
                 mtls_strict: bool = False, sidecar_injection_enabled: bool = True):
        self._access_log = access_log_enabled
        self._mtls_strict = mtls_strict
        self._sidecar = sidecar_injection_enabled

    def collect_operation_families(self): return IS_OPERATION_FAMILIES
    def collect_governance_layers(self, op_family):
        return [IS_GOVERNANCE_LAYERS[n] for n in op_family.declared_layers
                if n in IS_GOVERNANCE_LAYERS]
    def collect_executions(self, op_family):
        return [ExecutionInstance(
            operation_family=op_family.name,
            request_id=f"synthetic:{op_family.name}", timestamp="",
            policy_evaluated=True, sidecar_present=self._sidecar,
            access_log_written=self._access_log, mtls_verified=self._mtls_strict,
            source_principal=None, destination=None, result=None, error=None, raw={},
        )]

    def assess_k(self, inst):
        k = []
        fam = next((f for f in IS_OPERATION_FAMILIES if f.name == inst.operation_family), None)
        if not fam: return k
        if not inst.sidecar_present:
            return []  # BYPASS: sidecar absent = no Istio governance
        if "authorization_policy" in fam.declared_layers and inst.policy_evaluated:
            k.append("authorization_policy")
        if "envoy_access_log" in fam.declared_layers and inst.access_log_written:
            k.append("envoy_access_log")
        if "mtls_peer_auth" in fam.declared_layers and self._mtls_strict:
            k.append("mtls_peer_auth")
        if "peer_authentication" in fam.declared_layers:
            k.append("peer_authentication")
        if "mtls_cert" in fam.declared_layers and self._mtls_strict:
            k.append("mtls_cert")
        if "virtual_service" in fam.declared_layers:
            k.append("virtual_service")
        if "injection_webhook" in fam.declared_layers and self._sidecar:
            k.append("injection_webhook")
        if "envoy_config" in fam.declared_layers and self._sidecar:
            k.append("envoy_config")
        return k

    def assess_ear_state(self, op_family):
        if not self._sidecar: return EARState.ABSENT
        return EARState.CRYSTALLIZED

    def get_governance_declaration(self): return self.GOVERNANCE_DECLARATION
